apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: imanasipatilz/easycrud1-jenkins:backend
      ports:
        - containerPort: 80
